package edu.ucsd.som.stip.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * StipFund generated by hbm2java
 */
@Entity
@Table(name="stip_fund"
    ,catalog="stip"
)
public class StipFund  implements java.io.Serializable {

	private static final long serialVersionUID = 1585634949645247831L;
	
	private Integer stipFundId;
     private String quarter;
     private BigDecimal stipTotal;
     private String sourceFund;
     private String recipientFund;
     private String docNum;
     private Boolean status;
     private Date dateCreated;
     private Integer createdBy;
     private Date dateModified;
     private Integer modifiedBy;
     private String exclude;
     private String notes;

    public StipFund() {
    }

    public StipFund(String quarter, BigDecimal stipTotal, String sourceFund, String recipientFund, String docNum, Boolean status, Date dateCreated, Integer createdBy, Date dateModified, Integer modifiedBy, String exclude, String notes) {
       this.quarter = quarter;
       this.stipTotal = stipTotal;
       this.sourceFund = sourceFund;
       this.recipientFund = recipientFund;
       this.docNum = docNum;
       this.status = status;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.dateModified = dateModified;
       this.modifiedBy = modifiedBy;
       this.exclude = exclude;
       this.notes = notes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="stip_fund_id", unique=true, nullable=false)
    public Integer getStipFundId() {
        return this.stipFundId;
    }
    
    public void setStipFundId(Integer stipFundId) {
        this.stipFundId = stipFundId;
    }

    
    @Column(name="quarter", length=8)
    @Length(max=8)
    public String getQuarter() {
        return this.quarter;
    }
    
    public void setQuarter(String quarter) {
        this.quarter = quarter;
    }

    
    @Column(name="stip_total", precision=9)
    public BigDecimal getStipTotal() {
        return this.stipTotal;
    }
    
    public void setStipTotal(BigDecimal stipTotal) {
        this.stipTotal = stipTotal;
    }

    
    @Column(name="source_fund", length=6)
    @Length(max=6)
    public String getSourceFund() {
        return this.sourceFund;
    }
    
    public void setSourceFund(String sourceFund) {
        this.sourceFund = sourceFund;
    }

    
    @Column(name="recipient_fund", length=6)
    @Length(max=6)
    public String getRecipientFund() {
        return this.recipientFund;
    }
    
    public void setRecipientFund(String recipientFund) {
        this.recipientFund = recipientFund;
    }

    
    @Column(name="doc_num", length=10)
    @Length(max=10)
    public String getDocNum() {
        return this.docNum;
    }
    
    public void setDocNum(String docNum) {
        this.docNum = docNum;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="created_by")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_modified", length=19)
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    
    @Column(name="modified_by")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    
    @Column(name="Exclude", length=1)
    @Length(max=1)
    public String getExclude() {
        return this.exclude;
    }
    
    public void setExclude(String exclude) {
        this.exclude = exclude;
    }

    
    @Column(name="Notes", length=150)
    @Length(max=150)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


